# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2025 smdn <smdn@smdn.jp>"
#
# ref: https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
#
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:13"
      timezone: "Asia/Tokyo"
    assignees:
      - smdn
    groups:
      GitHub-Actions-Workflows:
        patterns:
          - "actions/*"
      GitHub-CodeQL-Actions:
        patterns:
          - "github/codeql-action/*"
      smdn-workflows-dotnet:
        patterns:
          - "smdn/workflows-dotnet/*"
    ignore:
      # smdn/workflows-dotnet: report major and minor updates only
      - dependency-name: "smdn/workflows-dotnet/*"
        update-types:
          - "version-update:semver-patch"
      # actions/checkout: report major updates only
      - dependency-name: "actions/checkout"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      # github/codeql-action: report major and minor updates only
      - dependency-name: "github/codeql-action/*"
        update-types:
          - "version-update:semver-patch"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - smdn
    groups:
      Smdn-MSBuild-ProjectAssets:
        patterns:
          - "Smdn.MSBuild.ProjectAssets.Common"
          - "Smdn.MSBuild.ProjectAssets.Library"
      NUnit:
        patterns:
          - "NUnit*"
    # Explicitly allow specific updates to ensure they aren't blocked by global ignore rules.
    allow:
      # For project SDK packages named with "Smdn.*", all updates should be reported.
      - dependency-name: "Smdn.MSBuild.ProjectAssets.*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      # For other packages, allow major updates (to be filtered by the ignore rule below).
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    ignore:
      # For Microsoft's extension packages, manually update them, so ignore all of them.
      - dependency-name: "Microsoft.Extensions.*"
        # No update-types; i.e., ignore any updates

        # For NUnit, Smdn.*, and other packages, only major updates should be reported.
        # (This rule acts as a global filter for any package not explicitly allowed for more.)
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
