// Smdn.Devices.MCP2221.GpioAdapter.dll (Smdn.Devices.MCP2221.GpioAdapter-0.9.2)
//   Name: Smdn.Devices.MCP2221.GpioAdapter
//   AssemblyVersion: 0.9.2.0
//   InformationalVersion: 0.9.2+bcf0f60c80f47181419bd376632a2c0be172ac98
//   TargetFramework: .NETCoreApp,Version=v8.0
//   Configuration: Release
//   Metadata: IsTrimmable=True
//   Metadata: RepositoryUrl=https://github.com/smdn/Smdn.Devices.MCP2221
//   Metadata: RepositoryBranch=main
//   Metadata: RepositoryCommit=bcf0f60c80f47181419bd376632a2c0be172ac98
//   Referenced assemblies:
//     Smdn.Devices.MCP2221, Version=0.9.4.0, Culture=neutral
//     System.Device.Gpio, Version=1.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
//     System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

using System;
using System.Device.I2c;
using Smdn.Devices.MCP2221;

namespace Smdn.Devices.MCP2221.GpioAdapter {
  public class MCP2221I2cDevice : I2cDevice {
    public MCP2221I2cDevice(MCP2221.I2CFunctionality i2cBus, I2CAddress i2cDeviceAddress) {}

    public I2CBusSpeed BusSpeed { get; set; }
    public override I2cConnectionSettings ConnectionSettings { get; }

    public override void Read(Span<byte> buffer) {}
    public override byte ReadByte() {}
    public override void Write(ReadOnlySpan<byte> buffer) {}
    public override void WriteByte(byte @value) {}
    public override void WriteRead(ReadOnlySpan<byte> writeBuffer, Span<byte> readBuffer) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.8.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.6.1.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
